[tool.black]
line-length = 120
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # black-default
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.poetry]
name = "toqito"
version = "1.0.5"
description = "Python tools for the study of quantum information."
authors = [
    "Vincent Russo <vincentrusso1@gmail.com>"
]
maintainers = [
    "Vincent Russo <vincentrusso1@gmail.com>"
]
readme = "README.md"
homepage = "https://vprusso.github.io/toqito/"
repository = "https://github.com/vprusso/toqito"
keywords = ["quantum information", "quantum computing", "nonlocal games"]


[tool.poetry.dependencies]
python = ">=3.10,<3.12"
cvxpy = "^1.2.1"
cvxopt = "^1.2.5"
numpy = "^1.19.4"
scipy = "^1.11.2"
#scs = "^2.1.2"
picos = "^2.0.30"

[tool.poetry.dev-dependencies]
black = "^21.10b0"
distlib = "^0.3.4"
flake8 = "^3.7"
flake8-docstrings = "^1.5"
ipython = "*"
isort = "^5.9.3"
myst-parser = "*"
pep8 = "^1.7"
ruff = "0.1.6"
pylint = "^2.4"
pytest = "*"
pytest-cov = "^4.1.0"
coverage = "^5.5"
mypy = "^1.3.0"
coveralls = "^1.9"
setuptools = ">65.5.1"
sphinx = "7.2.6"
sphinx_rtd_theme = "2.0.0rc4" # this version is temporary due to docutils version incompatibility with
# sphinx, sphinx_rtd_theme and sphinxcontrib-bibtex
sphinxcontrib-bibtex = "2.6.1"
sympy = "==1.12"


[build-system]
requires = ["setuptools","poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.ruff]
# exclude = ["__init__.py"]
line-length = 120
target-version = "py311"

[tool.ruff.lint]
select = ["I", "D"]
# ruff configuration
# E, W -- pycodestyle
# D -- pydocstyle
# I -- isort

# Rules considered over other incompatible ones
exclude = ["docs/conf.py", "setup.py"]
ignore = ["D407"]
# Rules Ignored
# D407 - Ignored because ==== under a section heading is considered as a missing underline.
# pydocstyle considers ----- an underline.

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["I001"]
# I001 - skip checking Import block is un-sorted or un-formatted